export const breakfastTypesList = [
  "American",
  "Asian",
  "Breakfast to go",
  "indian",
  "Halal",
  "Italian",
  "Kosher",
  "Vegan",
  "Buffet",
];

export const amenities = [
  "Restaurant",
  "Room service",
  "Bar",
  "24-hour front desk",
  "Sauna",
  "Fitness centre",
  "Garden",
  "Terrace",
  "Non-smoking rooms",
  "Airport shuttle",
  "Family rooms",
  "Spa and wellness centre",
  "Hot tub/Jacuzzi",
  "Free WiFi",
  "Air conditioning",
  "Water park",
  "Electric vehicle charging station",
  "Swimming pool",
  "Beach",
];

export const languages = [
  { value: "Afrikaans", label: "Afrikaans" },
  { value: "Albanian", label: "Albanian" },
  { value: "Amharic", label: "Amharic" },
  { value: "Arabic", label: "Arabic" },
  { value: "Armenian", label: "Armenian" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bengali", label: "Bengali" },
  { value: "Bosnian", label: "Bosnian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Catalan", label: "Catalan" },
  { value: "Chinese (Mandarin)", label: "Chinese (Mandarin)" },
  { value: "Chinese (Cantonese)", label: "Chinese (Cantonese)" },
  { value: "Croatian", label: "Croatian" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Dutch", label: "Dutch" },
  { value: "English", label: "English" },
  { value: "Filipino (Tagalog)", label: "Filipino (Tagalog)" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "German", label: "German" },
  { value: "Greek", label: "Greek" },
  { value: "Gujarati", label: "Gujarati" },
  { value: "Hebrew", label: "Hebrew" },
  { value: "Hindi", label: "Hindi" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Italian", label: "Italian" },
  { value: "Japanese", label: "Japanese" },
  { value: "Korean", label: "Korean" },
  { value: "Malay", label: "Malay" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Russian", label: "Russian" },
  { value: "Spanish", label: "Spanish" },
  { value: "Swedish", label: "Swedish" },
  { value: "Tamil", label: "Tamil" },
  { value: "Telugu", label: "Telugu" },
  { value: "Thai", label: "Thai" },
  { value: "Turkish", label: "Turkish" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Zulu", label: "Zulu" },
];

export const times = [
  "00:00",
  "01:00",
  "02:00",
  "03:00",
  "04:00",
  "05:00",
  "06:00",
  "07:00",
  "08:00",
  "09:00",
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
  "23:00",
];

export const timesList = [
  { label: "00:00", value: "00:00" },
  { label: "01:00", value: "01:00" },
  { label: "02:00", value: "02:00" },
  { label: "03:00", value: "03:00" },
  { label: "04:00", value: "04:00" },
  { label: "05:00", value: "05:00" },
  { label: "06:00", value: "06:00" },
  { label: "07:00", value: "07:00" },
  { label: "08:00", value: "08:00" },
  { label: "09:00", value: "09:00" },
  { label: "10:00", value: "10:00" },
  { label: "11:00", value: "11:00" },
  { label: "12:00", value: "12:00" },
  { label: "13:00", value: "13:00" },
  { label: "14:00", value: "14:00" },
  { label: "15:00", value: "15:00" },
  { label: "16:00", value: "16:00" },
  { label: "17:00", value: "17:00" },
  { label: "18:00", value: "18:00" },
  { label: "19:00", value: "19:00" },
  { label: "20:00", value: "20:00" },
  { label: "21:00", value: "21:00" },
  { label: "22:00", value: "22:00" },
  { label: "23:00", value: "23:00" },
  { label: "24:00", value: "24:00" },
];

export const roomFacilities = [
  "Balcony or Terrace",
  "Ensuite Bathroom",
  "Kitchenete or full kitchen",
  "Workspace/Desk",
  "Closet or wardrobe",
];

export const roomCategory = [
  { value: "Standard Room", label: "Standard Room" },
  { value: "Deluxe Room", label: "Deluxe Room" },
  { value: "Superior Room", label: "Superior Room" },
  { value: "Executive Room", label: "Executive Room" },
  { value: "Suite", label: "Suite" },
  { value: "Presidential Suite", label: "Presidential Suite" },
  { value: "Villa", label: "Villa" },
  { value: "Cabana", label: "Cabana" },
  { value: "Family Room", label: "Family Room" },
  { value: "Studio", label: "Studio" },
];

export const bedType = [
  { value: "Single Bed", label: "Single Bed" },
  { value: "Double Bed", label: "Double Bed" },
  { value: "Queen Bed", label: "Queen Bed" },
  { value: "King Bed", label: "King Bed" },
  { value: "Twin Beds", label: "Twin Beds" },
  { value: "Sofa Bed", label: "Sofa Bed" },
  { value: "Bunk Bed", label: "Bunk Bed" },
  { value: "Rollaway Bed", label: "Rollaway Bed" },
  { value: "Murphy Bed", label: "Murphy Bed" },
  { value: "Day Bed", label: "Day Bed" },
];
export const roomView = [
  { value: "City View", label: "City View" },
  { value: "Garden View", label: "Garden View" },
  { value: "Forest View", label: "Forest View" },
];
export const roomType = [
  { value: "Single Room", label: "Single Room" },
  { value: "Double Room", label: "Double Room" },
  { value: "Twin Room", label: "Twin Room" },
  { value: "Triple Room", label: "Triple Room" },
  { value: "Quad Room", label: "Quad Room" },
  { value: "Accessible Room", label: "Accessible Room" },
  { value: "Connecting Room", label: "Connecting Room" },
  { value: "Penthouse", label: "Penthouse" },
];

export const paymentStatus = [
  { value: "Pending", label: "Pending" },
  { value: "Paid", label: "Paid" },
  { value: "Failed", label: "Failed" },
];

export const bookingStatus = [
  { label: "Pending", value: "Pending" },
  { label: "Confirmed", value: "Confirmed" },
  { label: "Cancelled", value: "Cancelled" },
  { label: "Completed", value: "Completed" },
];
